version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    volumes:
      - ../../:/app
    restart: unless-stopped 