FROM golang:1.24-alpine

WORKDIR /app

# Install necessary tools
RUN apk --no-cache add curl bash

# Create bin directory
RUN mkdir -p /app/bin

# Copy entrypoint script
COPY infra/docker/docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

# Expose port
EXPOSE 8080

# Use entrypoint script to build and run the app
ENTRYPOINT ["/docker-entrypoint.sh"] 