services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - GO111MODULE=on
      - CGO_ENABLED=0
    volumes:
      - ../../:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ls", "-la", "/app/bin"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s 